make_csv: True
data_dir: "dags/extract/data"
territories_dir: "dags/extract/territories"

test_mode: True
n: 3

jobs_alphabetical_url: "https://candidat.francetravail.fr/gw-metierscope/jobs/groupByFirstLetter"
domains_url: "https://candidat.francetravail.fr/gw-metierscope/domains"
domain_url: "https://candidat.francetravail.fr/gw-metierscope/domain"
url_job: "https://candidat.francetravail.fr/gw-metierscope/job/"

gcp_project_id: "project-addc57f7-fb9f-4221-a91"  # ENTER YOUR OWN PROJECT ID HERE
gcs_bucket_name: "ft_data_files_bucket"
bq_dataset_name: "FT_data"
